/* This file is autogenerated, do not edit*/
#include "moc_fscontrolpanel.cpp"
#include "moc_fsdialog.cpp"
#include "moc_fsserial.cpp"
#include "moc_fswebcam.cpp"
#include "moc_mainwidget.cpp"
#include "moc_mainwindow.cpp"
